package my.FactorialandGCD;

import static numeric.Factorial.factor;

/**
* This class implements the GCD and Factorial classes, providing support for manipulation
* of numbers.
*
* @author Emily Wolf
* @version 1.0
* File: GCDandFactorial.java
* Created: Sept 2015
* Summary of Modifications:
* 17 Sept 2015 – ERW – fixed clearing of error messages
*
* Description: This class provides the GUI for implementing the factorial and GCD classes.
*/
public class GCDandFactorialUI extends javax.swing.JFrame {

    /**
     * Creates new form GCDandFactorialUI
     */
    public GCDandFactorialUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        factDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        factInput = new javax.swing.JTextField();
        ErrorMess = new javax.swing.JLabel();
        FactAnswer = new javax.swing.JLabel();
        FactSolve = new javax.swing.JButton();
        factClear = new javax.swing.JButton();
        GCDDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        GCDInput1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        GCDInput2 = new javax.swing.JTextField();
        inputError = new javax.swing.JLabel();
        GCDAnswer = new javax.swing.JLabel();
        SolveGCD = new javax.swing.JToggleButton();
        GCDClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Fact = new javax.swing.JButton();
        GCD = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Compute = new javax.swing.JMenu();
        menuGCD = new javax.swing.JMenuItem();
        menuFact = new javax.swing.JMenuItem();

        factDialog.setTitle("Factorialing!");
        factDialog.setMinimumSize(new java.awt.Dimension(230, 250));
        factDialog.setModal(true);

        jLabel2.setText("Enter an int: ");
        jLabel2.setToolTipText("");

        factInput.setMinimumSize(new java.awt.Dimension(100, 26));
        factInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factInputActionPerformed(evt);
            }
        });

        ErrorMess.setForeground(new java.awt.Color(255, 0, 51));

        FactSolve.setText("Solve");
        FactSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactSolveActionPerformed(evt);
            }
        });

        factClear.setText("Clear");
        factClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout factDialogLayout = new javax.swing.GroupLayout(factDialog.getContentPane());
        factDialog.getContentPane().setLayout(factDialogLayout);
        factDialogLayout.setHorizontalGroup(
            factDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factDialogLayout.createSequentialGroup()
                .addGroup(factDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(factDialogLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(factDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(factDialogLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(factInput, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(factDialogLayout.createSequentialGroup()
                                .addComponent(FactSolve)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(factClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ErrorMess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(factDialogLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(FactAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        factDialogLayout.setVerticalGroup(
            factDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factDialogLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(factDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMess, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(factDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FactSolve)
                    .addComponent(factClear))
                .addGap(18, 18, 18)
                .addComponent(FactAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        GCDDialog.setTitle("GCDing!");
        GCDDialog.setMinimumSize(new java.awt.Dimension(300, 300));
        GCDDialog.setModal(true);

        jLabel1.setText("Enter your first integer:");

        GCDInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCDInput1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter your second integer:");

        GCDInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCDInput2ActionPerformed(evt);
            }
        });

        inputError.setForeground(new java.awt.Color(255, 0, 51));

        SolveGCD.setText("Solve");
        SolveGCD.setOpaque(true);
        SolveGCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveGCDActionPerformed(evt);
            }
        });

        GCDClear.setText("Clear");
        GCDClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCDClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GCDDialogLayout = new javax.swing.GroupLayout(GCDDialog.getContentPane());
        GCDDialog.getContentPane().setLayout(GCDDialogLayout);
        GCDDialogLayout.setHorizontalGroup(
            GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GCDDialogLayout.createSequentialGroup()
                .addGroup(GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GCDDialogLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GCDAnswer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GCDDialogLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GCDInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GCDDialogLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GCDInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(GCDDialogLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputError, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GCDDialogLayout.createSequentialGroup()
                                .addComponent(SolveGCD)
                                .addGap(18, 18, 18)
                                .addComponent(GCDClear)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        GCDDialogLayout.setVerticalGroup(
            GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GCDDialogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GCDInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GCDInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SolveGCD)
                    .addComponent(GCDClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GCDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GCDAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(inputError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMinimumSize(new java.awt.Dimension(190, 190));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 200));

        Fact.setText("Factorial");
        Fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactActionPerformed(evt);
            }
        });

        GCD.setText("GCD");
        GCD.setMaximumSize(new java.awt.Dimension(100, 29));
        GCD.setMinimumSize(new java.awt.Dimension(100, 29));
        GCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fact, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GCD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fact)
                    .addComponent(GCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        Compute.setText("Compute");

        menuGCD.setText("GCD");
        menuGCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGCDActionPerformed(evt);
            }
        });
        Compute.add(menuGCD);

        menuFact.setText("Factorial");
        menuFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFactActionPerformed(evt);
            }
        });
        Compute.add(menuFact);

        jMenuBar1.add(Compute);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void FactActionPerformed(java.awt.event.ActionEvent evt) {                                     
       factDialog.setVisible(true);
    }                                    

    private void GCDActionPerformed(java.awt.event.ActionEvent evt) {                                    
       GCDDialog.setVisible(true);
    }                                   

    private void factInputActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }                                         

    private void FactSolveActionPerformed(java.awt.event.ActionEvent evt) {                                          

    //checking for proper input
    try {
      ErrorMess.setText("");
      FactAnswer.setText("");
      double num = Integer.parseInt(factInput.getText());
      if (num < 0) {
          throw new numeric.NegativeNumberException("");
      }
    //running only if no exception  
    FactAnswer.setText("It's " +Double.toString(numeric.Factorial.factor(num)));
    }
    //different exceptions
    catch (NumberFormatException a) {
        ErrorMess.setText("Please enter a valid integer.");
        factInput.setText("");
    }
    catch (numeric.NegativeNumberException b) {
        ErrorMess.setText("Please enter a positive integer.");
        factInput.setText("");
    }
         


    }                                         

    private void GCDInput1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void SolveGCDActionPerformed(java.awt.event.ActionEvent evt) {                                         

    //checking for proper input
    try {
      GCDAnswer.setText("");
      inputError.setText("");
      int num1 = Integer.parseInt(GCDInput1.getText());
      int num2 = Integer.parseInt(GCDInput2.getText());
      GCDAnswer.setText("It's " + Double.toString(numeric.GCD.GCD(num1,num2)));
    }
    //improper input
    catch (NumberFormatException a) {
      inputError.setText("Please enter two valid integers.");
      GCDInput1.setText("");
      GCDInput2.setText("");
    }
         


    }                                        

    private void GCDClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //clearing everything
        GCDAnswer.setText("");
        GCDInput1.setText("");
        GCDInput2.setText("");
        inputError.setText("");
    }                                        

    private void factClearActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //clearing everything
        FactAnswer.setText("");
        ErrorMess.setText("");
        factInput.setText("");
    }                                         

    private void menuGCDActionPerformed(java.awt.event.ActionEvent evt) {                                        
       GCDDialog.setVisible(true);
    }                                       

    private void menuFactActionPerformed(java.awt.event.ActionEvent evt) {                                         
       factDialog.setVisible(true);
    }                                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    System.exit(0);
    }                                          

    private void GCDInput2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GCDandFactorialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GCDandFactorialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GCDandFactorialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GCDandFactorialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GCDandFactorialUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu Compute;
    private javax.swing.JLabel ErrorMess;
    private javax.swing.JButton Fact;
    private javax.swing.JLabel FactAnswer;
    private javax.swing.JButton FactSolve;
    private javax.swing.JButton GCD;
    private javax.swing.JLabel GCDAnswer;
    private javax.swing.JButton GCDClear;
    private javax.swing.JDialog GCDDialog;
    private javax.swing.JTextField GCDInput1;
    private javax.swing.JTextField GCDInput2;
    private javax.swing.JToggleButton SolveGCD;
    private javax.swing.JButton factClear;
    private javax.swing.JDialog factDialog;
    private javax.swing.JTextField factInput;
    private javax.swing.JLabel inputError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuFact;
    private javax.swing.JMenuItem menuGCD;
    // End of variables declaration                   
}
